# Monefy Bug Report - Detailed Analysis 📋

## Complete Bug Report Table

| Bug ID | Title | Severity | Priority | Impact | Reproducible Steps | Affected Devices | Network |
|--------|-------|----------|----------|--------|-------------------|------------------|---------|
| **MON-001** | **Currency change updates payment icons but not monetary values** | 🔴 High | 🔴 High | Users see incorrect monetary values when switching currencies. Euro=Dollar=EGY which is not true | 1. Open Monefy app<br>2. Add payment entries using USD currency<br>3. Navigate to currency settings<br>4. Change currency from USD to Euro<br>5. Return to home screen<br>6. Observe currency icons change but values remain unchanged | Samsung Galaxy A35<br>Android | Online |
| **MON-002** | **App crashes when returning to home page after changing date interval** | 🔴 High | 🔴 High | Users cannot return to home page after modifying date filters, making the app unusable and forcing restart | 1. Open Monefy app<br>2. Verify payment entries displayed (4 days: 26th-29th)<br>3. Access date interval/filter settings<br>4. Change date range (20th-31st)<br>5. Apply new date filter<br>6. Navigate back to home page<br>7. App crashes | Samsung Galaxy A35<br>Android | Online |
| **MON-003** | **Budget mode notifications not functioning** | 🟡 Medium | 🟡 Medium | Users cannot receive budget notifications when spending exceeds limits - budget tracking feature doesn't work | 1. Open Monefy app<br>2. Navigate to Settings<br>3. Enable Budget mode (ON)<br>4. Set budget limits to 50,000<br>5. Make payments exceeding 50,000<br>6. Observe no notifications appear | Samsung Galaxy A35<br>Android | Online |
| **MON-004** | **Tutorial popup appears in wrong position and persists across navigation** | 🟡 Medium | 🟡 Medium | New users experience poor first impression due to misaligned tutorial popups and navigation interference | 1. Install Monefy as new user OR clear app data<br>2. Launch app for first time<br>3. Observe tutorial/onboarding popup<br>4. Navigate to different pages<br>5. Popup remains visible across page changes | Samsung Galaxy A35<br>Android | Online |
| **MON-005** | **Incorrect percentage calculations in donut chart with 5+ payments** | 🔴 High | 🟡 Medium | Users receive incorrect financial insights due to wrong percentage calculations regardless of time interval selected | 1. Open Monefy app<br>2. Add 5+ payments across different categories<br>3. Navigate to any time interval view<br>4. Access donut chart in statistics<br>5. Compare percentages with actual amounts<br>6. Test across different time intervals | Samsung Galaxy A35<br>Android | Online |
| **MON-006** | **Incomplete language translation** | 🟢 Low | 🟡 Medium | Users experience inconsistent localization with mixed languages, creating confusion for non-native speakers | 1. Open Monefy app<br>2. Navigate to Settings<br>3. Change app language<br>4. Apply language change<br>5. Navigate through different sections<br>6. Observe mixed languages throughout interface | Samsung Galaxy A35<br>Android | Online |
| **MON-007** | **Calculator accepts incomplete expressions and returns incorrect results** | 🟡 Medium | 🟡 Medium | Users may unknowingly enter incomplete expressions and receive wrong calculation results, leading to incorrect payment amounts | 1. Open Monefy app<br>2. Navigate to calculator<br>3. Enter complete expression (3+3) - verify works<br>4. Enter incomplete expression (3+)<br>5. Press equals<br>6. Observe incorrect numerical result instead of error<br>7. Test with other operators | Samsung Galaxy A35<br>Android | Online |
| **MON-008** | **Income/Expense buttons display symbols instead of text labels** | 🟢 Low | 🟡 Medium | Users experience confusion when primary buttons show mathematical symbols instead of clear descriptive labels, reducing interface clarity | 1. Open Monefy app<br>2. Navigate to home page<br>3. Locate Income and Expense buttons<br>4. Verify buttons should show "Income"/"Expense" text<br>5. Observe "+"/"−" symbols instead | Samsung Galaxy A35<br>Android | Online |
